/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minifyjpeg.h"

bool_t
xdr_minify_img_arg (XDR *xdrs, minify_img_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->src_buf.src_buf_val, (u_int *) &objp->src_buf.src_buf_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dest_buffer (XDR *xdrs, dest_buffer *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->dest_buf.dest_buf_val, (u_int *) &objp->dest_buf.dest_buf_len, ~0))
		 return FALSE;
	return TRUE;
}
