/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "minifyjpeg.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
minify_image_1(minify_img_arg arg1, dest_buffer *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, minify_image,
		(xdrproc_t) xdr_minify_img_arg, (caddr_t) &arg1,
		(xdrproc_t) xdr_dest_buffer, (caddr_t) clnt_res,
		TIMEOUT));
}
